### ISSUE TITLE
The exported .p12 file can not be imported into Windows

### ISSUE THREAD

**Issue by ssonow** [olivierlemasle/java-certificate-authority#1]
Error is : an internal error occurred. Either the user profile is not accessible or the private key that you are importing might require a cryptographic service provider that is not installed on your system. 

Need to change java.security?

**Comment by olivierlemasle** [comment]
Hi,

This exact error message is referenced here: https://support.microsoft.com/en-us/kb/919074
Could you please check the three causes and possible resolutions and tell me if it helped?

Thanks!

**Comment by ssonow** [comment]
Have you tried to load it into OS yourself? I have tried MAC and Windows,
none worked.

I have attached code and one bad output.  Password is "password".

Thanks!

**Comment by olivierlemasle** [comment]
Yes, I tried and it works. Your code and output were not attached to GitHub issue. Can you please paste it directly in the issue?

**Comment by olivierlemasle** [comment]
Simple example:

``` java
import static io.github.olivierlemasle.ca.CA.createSelfSignedCertificate;
import static io.github.olivierlemasle.ca.CA.dn;

import io.github.olivierlemasle.ca.DistinguishedName;
import io.github.olivierlemasle.ca.RootCertificate;

public class Main {

  public static void main(final String[] args) {
    final DistinguishedName root = dn("CN=Root-Test, O=My Org");
    final RootCertificate ca = createSelfSignedCertificate(root)
        .validDuringYears(10)
        .build();
    ca.exportPkcs12("root.p12", "password".toCharArray(), "test");
  }
}
```

I successfully read it on my main OS (Linux Fedora).
Now, on Windows 10:

![2016-06-05 12_31_33-clipboard](https://cloud.githubusercontent.com/assets/628140/15804905/9bb6fe96-2b19-11e6-86a1-520cbae90ae8.png)

Then I select "Local Machine", then the root.p12 path, then:

![2016-06-05 12_35_08-](https://cloud.githubusercontent.com/assets/628140/15804918/ff718384-2b19-11e6-8471-32aee4620bde.png)

Then I choose the store (Personal in my case), and review the settings.
And finally:

![2016-06-05 12_37_44-certificate import wizard](https://cloud.githubusercontent.com/assets/628140/15804942/67a79f10-2b1a-11e6-990a-aa9b4bfe299b.png)

![2016-06-05 12_38_05-certlm - certificates - local computer_personal_certificates](https://cloud.githubusercontent.com/assets/628140/15804943/6bef86fa-2b1a-11e6-82a6-75935eb19fcd.png)

I can now check that the SSL certificate is imported, along with the private key.

**Comment by monkeyk** [comment]
Suggest more OS platform testing @olivierlemasle 
i had the same issue when import certificate(.p12 file) on Win7 and MAC,
but import on Win10 is OK,  why?? confused.

win7 error: [http://andaily.com/dd/win7_error.png](http://andaily.com/dd/win7_error.png)
Mac error: [http://andaily.com/dd/mac_error.png](http://andaily.com/dd/mac_error.png)

**Comment by monkeyk** [comment]
I found the issue and update it
` keyStore.setKeyEntry(alias, privateKey, keystorePassword, chain);`
must set keystorePassword

and when load from Keystore, add password
`  final PrivateKey privateKey = (PrivateKey) keystore.getKey(alias, password);`

**Comment by olivierlemasle** [comment]
Closing as I archive this unmaintained project.
